# Site settings
title: Alokiria Blog
SEOTitle: 江若水的博客 | Alokiria Blog
header-img: img/bg-home.jpg
email: jyh752038321@outlook.com
description: "这里是 @Alokiria 的个人博客，那么朋友，你听说过东方Project吗"
keyword: "江若水, Alokiria, Alokiria江若水, @Alokiria, Alokiria的博客, AlokriaBlog, 博客, 个人网站, TA, Shader, Unity, 插画, 图形学, 渲染, 设计"
url: "https://Alokiria.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: u/7795048807
zhihu_username: alokiria
github_username: Alokiria
twitter_username: likwater34940
#facebook_username:  Alokiria
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: Alokiria

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: alokiria.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "一定要学会放过自己 <br> Tower Of Galaxy @ Alokiria"
sidebar-avatar: https://raw.githubusercontent.com/Alokiria/Alokiria.github.io/refs/heads/master/img/avatar.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "无", href: "http://XXX.com/" },

  ]
